apiVersion: v2
name: kube-prometheus-rules
description: Community-inspired Prometheus alerting rules for Kubernetes observability (PVC, node, pod, disk)
type: application
version: 0.13.1
appVersion: "1.0.0"
maintainers:
  - name: lop3z
