apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-cert
spec:
  commonName: vault
  usages:
    - server auth
  dnsNames:
    - vault
    - vault.{{ .Release.Namespace }}
    - vault.{{ .Release.Namespace }}.svc
    - vault.{{ .Release.Namespace }}.svc.cluster.local
  ipAddresses:
    - 127.0.0.1
  secretName: vault-cert-tls
  issuerRef:
    name: vault-selfsigned
EOF