# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: vault-file
# spec:
#   # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
# {{- if .Values.pvc.storageClassName }}
#   storageClassName: '{{ .Values.pvc.storageClassName }}'
# {{- end }}
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: {{ .Values.pvc.size }}
