---
apiVersion: v1
kind: Service
metadata:
  name: "vault"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    app.kubernetes.io/name: vault
    example.com/log-format: json
    global_service: 'true'
    vault_cr: vault
  annotations:
    common/annotation: 'true'
    service.cilium.io/global: 'true'
    type/instance: vault
spec:
  ports:
    - name: api-port
      protocol: TCP
      port: 8200
      targetPort: 8200
    - name: cluster-port
      protocol: TCP
      port: 8201
      targetPort: 8201
    - name: metrics
      protocol: TCP
      port: 9091
      targetPort: 9091
    - name: statsd
      protocol: TCP
      port: 9102
      targetPort: 9102
  selector:
    app.kubernetes.io/name: vault
    vault-active: 'true'
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
{{- range $key, $region :=  .Values.multiRegion }}
{{- if not (contains $region $.Release.Name) }}
---
apiVersion: v1
kind: Service
metadata:
  name: "vault-{{ $region }}"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    app.kubernetes.io/name: vault
    example.com/log-format: json
    global_service: 'true'
    vault_cr: vault-{{ $region }}
  annotations:
    common/annotation: 'true'
    service.cilium.io/global: 'true'
    type/instance: vault
spec:
  ports:
    - name: api-port
      protocol: TCP
      port: 8200
      targetPort: 8200
    - name: cluster-port
      protocol: TCP
      port: 8201
      targetPort: 8201
    - name: metrics
      protocol: TCP
      port: 9091
      targetPort: 9091
    - name: statsd
      protocol: TCP
      port: 9102
      targetPort: 9102
  selector:
    app.kubernetes.io/name: vault
    vault-active: 'true'
    vault_cr: vault-{{ $region }}
  type: ClusterIP
  sessionAffinity: None
  publishNotReadyAddresses: true
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
{{- range $i := until ($.Values.size | int) }}
---
apiVersion: v1
kind: Service
metadata:
  name: "vault-{{ $region }}-{{ . }}"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    app.kubernetes.io/name: vault
    example.com/log-format: json
    global_service: 'true'
    vault_cr: vault-{{ $region }}-{{ . }}
  annotations:
    common/annotation: 'true'
    service.cilium.io/global: 'true'
    type/instance: vault
spec:
  ports:
    - name: api-port
      protocol: TCP
      port: 8200
      targetPort: 8200
    - name: cluster-port
      protocol: TCP
      port: 8201
      targetPort: 8201
    - name: metrics
      protocol: TCP
      port: 9091
      targetPort: 9091
    - name: statsd
      protocol: TCP
      port: 9102
      targetPort: 9102
  selector:
    app.kubernetes.io/name: vault
    vault-active: 'true'
    vault_cr: "vault-{{ $region }}-{{ . }}"
  type: ClusterIP
  sessionAffinity: None
  publishNotReadyAddresses: true
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
{{- end }}   
{{- end }}   
{{- end }}   

