apiVersion: v1
kind: Secret
metadata:
  name: keycloak-cnpg-s3
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  ACCESS_KEY_ID: {{ .Values.s3.accessKeyId }}
  ACCESS_SECRET_KEY: {{ .Values.s3.accessSecretKey }}
