apiVersion: v1
kind: Secret
metadata:
  name: keycloak-cnpg-app
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: keycloak
  password: {{ .Values.postgresql.password }}
