{{- if .Values.disruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-pdb
spec:
  minAvailable: {{ .Values.disruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-wireguard"
{{- end }}
