{{- range .Values.externalServices }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: netbird-access
spec:
  type: ClusterIP
  ports:
  - name: {{ .portName | default "tcp" }}
    port: {{ .port }}
    targetPort: {{ .port }}
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: netbird-access
subsets:
- addresses:
  - ip: {{ .externalHost }}
  ports:
  - name: {{ .portName | default "tcp" }}
    port: {{ .port }}
    protocol: TCP
{{- end }}
