{{- if not .Values.apiKey.existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "hyperping-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hyperping-exporter.labels" . | nindent 4 }}
stringData:
  HYPERPING_API_KEY: {{ .Values.apiKey.value | quote }}
{{- end }}
