apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyperping-exporter.fullname" . }}
  labels:
    {{- include "hyperping-exporter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.config.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "hyperping-exporter.selectorLabels" . | nindent 4 }}
