{{- if .Values.rules.node.enabled }}
{{- $sevWarn := ternary "wip_warning" "warning" .Values.rules.node.warningSuppressed }}
{{- $sevCrit := ternary "wip_critical" "critical" .Values.rules.node.criticalSuppressed }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-node
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-prometheus-rules.labels" . | nindent 4 }}
    gitops.jenkins-x.io/pipeline: namespaces
spec:
  groups:
  - name: kubernetes.node
    rules:
    - alert: KubeNodeMemoryHigh
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} memory usage is
          {{ "{{" }} printf "%.0f" $value {{ "}}" }}% on cluster {{ "{{" }} $labels.cluster_region {{ "}}" }}.
        summary: Node memory usage high ({{ "{{" }} $labels.cluster_region {{ "}}" }})
        {{- with (.Values.runbooks.node.memoryHigh | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          1 - (
            node_memory_MemAvailable_bytes
            / node_memory_MemTotal_bytes
          )
        ) * 100 > {{ .Values.rules.node.memoryWarningThreshold }}
      for: 5m
      labels:
        severity: {{ $sevWarn }}

    - alert: KubeNodeMemoryHigh
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} memory usage is
          {{ "{{" }} printf "%.0f" $value {{ "}}" }}% on cluster {{ "{{" }} $labels.cluster_region {{ "}}" }}.
          Immediate action required.
        summary: Node memory critically high ({{ "{{" }} $labels.cluster_region {{ "}}" }})
        {{- with (.Values.runbooks.node.memoryHigh | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          1 - (
            node_memory_MemAvailable_bytes
            / node_memory_MemTotal_bytes
          )
        ) * 100 > {{ .Values.rules.node.memoryCriticalThreshold }}
      for: 5m
      labels:
        severity: {{ $sevCrit }}

    - alert: KubeNodeCPUSaturation
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} CPU usage is
          {{ "{{" }} printf "%.0f" $value {{ "}}" }}% on cluster {{ "{{" }} $labels.cluster_region {{ "}}" }}.
        summary: Node CPU saturation ({{ "{{" }} $labels.cluster_region {{ "}}" }})
        {{- with (.Values.runbooks.node.cpuSaturation | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          1 - avg by (cluster_region, instance) (
            rate(node_cpu_seconds_total{mode="idle"}[5m])
          )
        ) * 100 > {{ .Values.rules.node.cpuWarningThreshold }}
      for: 5m
      labels:
        severity: {{ $sevWarn }}

    - alert: KubeNodeCPUSaturation
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} CPU usage is
          {{ "{{" }} printf "%.0f" $value {{ "}}" }}% on cluster {{ "{{" }} $labels.cluster_region {{ "}}" }}.
          Immediate action required.
        summary: Node CPU critically saturated ({{ "{{" }} $labels.cluster_region {{ "}}" }})
        {{- with (.Values.runbooks.node.cpuSaturation | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          1 - avg by (cluster_region, instance) (
            rate(node_cpu_seconds_total{mode="idle"}[5m])
          )
        ) * 100 > {{ .Values.rules.node.cpuCriticalThreshold }}
      for: 5m
      labels:
        severity: {{ $sevCrit }}

    - alert: KubeNodeFilesystemAlmostFull
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} root filesystem is
          {{ "{{" }} printf "%.0f" $value {{ "}}" }}% full on cluster {{ "{{" }} $labels.cluster_region {{ "}}" }}.
        summary: Node root filesystem almost full ({{ "{{" }} $labels.cluster_region {{ "}}" }})
        {{- with (.Values.runbooks.node.filesystemAlmostFull | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          1 - (
            node_filesystem_avail_bytes{
              mountpoint="/",
              fstype!~"tmpfs|fuse.lxcfs|squashfs"
            }
            / node_filesystem_size_bytes{
              mountpoint="/",
              fstype!~"tmpfs|fuse.lxcfs|squashfs"
            }
          )
        ) * 100 > {{ .Values.rules.node.diskWarningThreshold }}
      for: 10m
      labels:
        severity: {{ $sevWarn }}

    - alert: KubeNodeFilesystemAlmostFull
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} root filesystem is
          {{ "{{" }} printf "%.0f" $value {{ "}}" }}% full on cluster {{ "{{" }} $labels.cluster_region {{ "}}" }}.
          Immediate action required.
        summary: Node root filesystem critically full ({{ "{{" }} $labels.cluster_region {{ "}}" }})
        {{- with (.Values.runbooks.node.filesystemAlmostFull | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          1 - (
            node_filesystem_avail_bytes{
              mountpoint="/",
              fstype!~"tmpfs|fuse.lxcfs|squashfs"
            }
            / node_filesystem_size_bytes{
              mountpoint="/",
              fstype!~"tmpfs|fuse.lxcfs|squashfs"
            }
          )
        ) * 100 > {{ .Values.rules.node.diskCriticalThreshold }}
      for: 10m
      labels:
        severity: {{ $sevCrit }}

    - alert: KubeNodeInodesSaturation
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} inode usage is
          {{ "{{" }} printf "%.0f" $value {{ "}}" }}% on cluster {{ "{{" }} $labels.cluster_region {{ "}}" }}.
        summary: Node root filesystem inode saturation ({{ "{{" }} $labels.cluster_region {{ "}}" }})
        {{- with (.Values.runbooks.node.inodesSaturation | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          1 - (
            node_filesystem_files_free{
              mountpoint="/",
              fstype!~"tmpfs|fuse.lxcfs|squashfs"
            }
            / node_filesystem_files{
              mountpoint="/",
              fstype!~"tmpfs|fuse.lxcfs|squashfs"
            }
          )
        ) * 100 > {{ .Values.rules.node.inodeWarningThreshold }}
      for: 10m
      labels:
        severity: {{ $sevWarn }}

    - alert: KubeNodeInodesSaturation
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} inode usage is
          {{ "{{" }} printf "%.0f" $value {{ "}}" }}% on cluster {{ "{{" }} $labels.cluster_region {{ "}}" }}.
          Immediate action required.
        summary: Node root filesystem inodes critically saturated ({{ "{{" }} $labels.cluster_region {{ "}}" }})
        {{- with (.Values.runbooks.node.inodesSaturation | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          1 - (
            node_filesystem_files_free{
              mountpoint="/",
              fstype!~"tmpfs|fuse.lxcfs|squashfs"
            }
            / node_filesystem_files{
              mountpoint="/",
              fstype!~"tmpfs|fuse.lxcfs|squashfs"
            }
          )
        ) * 100 > {{ .Values.rules.node.inodeCriticalThreshold }}
      for: 10m
      labels:
        severity: {{ $sevCrit }}

    - alert: KubeNodeFilesystemSpaceFillingUp
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} root filesystem is predicted to fill up
          within 24 hours on cluster {{ "{{" }} $labels.cluster_region {{ "}}" }}.
        summary: Node root filesystem predicted to be full in 24h ({{ "{{" }} $labels.cluster_region {{ "}}" }})
        {{- with (.Values.runbooks.node.filesystemSpaceFillingUp | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          node_filesystem_avail_bytes{
            mountpoint="/",
            fstype!~"tmpfs|fuse.lxcfs|squashfs"
          } / node_filesystem_size_bytes{
            mountpoint="/",
            fstype!~"tmpfs|fuse.lxcfs|squashfs"
          } * 100 < 15
        )
        and
        predict_linear(
          node_filesystem_avail_bytes{
            mountpoint="/",
            fstype!~"tmpfs|fuse.lxcfs|squashfs"
          }[6h],
          86400
        ) < 0
      for: 1h
      labels:
        severity: {{ $sevWarn }}

    - alert: KubeNodePressure
      annotations:
        description: >
          Node {{ "{{" }} $labels.node {{ "}}" }} has {{ "{{" }} $labels.condition {{ "}}" }}
          pressure on cluster {{ "{{" }} $labels.cluster_region {{ "}}" }}.
        summary: Node pressure condition active ({{ "{{" }} $labels.cluster_region {{ "}}" }})
        {{- with (.Values.runbooks.node.pressure | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        kube_node_status_condition{
          condition=~"MemoryPressure|DiskPressure|PIDPressure",
          status="true"
        } == 1
      for: 10m
      labels:
        severity: {{ $sevWarn }}

    - alert: KubeNodeLoadHigh
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} normalized load is
          {{ "{{" }} printf "%.2f" $value {{ "}}" }}x on cluster {{ "{{" }} $labels.cluster_region {{ "}}" }}.
        summary: Node load saturation high ({{ "{{" }} $labels.cluster_region {{ "}}" }})
        {{- with (.Values.runbooks.node.loadHigh | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          node_load15
          / on(cluster_region, instance)
          count by (cluster_region, instance) (
            node_cpu_seconds_total{mode="idle"}
          )
        ) > {{ .Values.rules.node.loadWarningRatio }}
      for: 10m
      labels:
        severity: {{ $sevWarn }}

    - alert: KubeNodeLoadHigh
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} normalized load is
          {{ "{{" }} printf "%.2f" $value {{ "}}" }}x on cluster {{ "{{" }} $labels.cluster_region {{ "}}" }}.
          Immediate action required.
        summary: Node load critically saturated ({{ "{{" }} $labels.cluster_region {{ "}}" }})
        {{- with (.Values.runbooks.node.loadHigh | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          node_load15
          / on(cluster_region, instance)
          count by (cluster_region, instance) (
            node_cpu_seconds_total{mode="idle"}
          )
        ) > {{ .Values.rules.node.loadCriticalRatio }}
      for: 10m
      labels:
        severity: {{ $sevCrit }}
{{- end }}
