{{- if .Values.rules.node.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-node
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-prometheus-rules.labels" . | nindent 4 }}
    gitops.jenkins-x.io/pipeline: namespaces
spec:
  groups:
  - name: kubernetes.node
    rules:
    - alert: KubeNodeMemoryHigh
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} memory usage is
          {{ "{{" }} printf "%.0f" $value {{ "}}" }}% on cluster {{ .Values.clusterRegion }}.
        summary: Node memory usage high ({{ .Values.clusterRegion }})
        {{- with (.Values.runbooks.node.memoryHigh | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          1 - (
            node_memory_MemAvailable_bytes{cluster_region="{{ .Values.clusterRegion }}"}
            / node_memory_MemTotal_bytes{cluster_region="{{ .Values.clusterRegion }}"}
          )
        ) * 100 > {{ .Values.rules.node.memoryWarningThreshold }}
      for: 5m
      labels:
        severity: warning
        cluster_region: {{ .Values.clusterRegion }}

    - alert: KubeNodeMemoryHigh
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} memory usage is
          {{ "{{" }} printf "%.0f" $value {{ "}}" }}% on cluster {{ .Values.clusterRegion }}.
          Immediate action required.
        summary: Node memory critically high ({{ .Values.clusterRegion }})
        {{- with (.Values.runbooks.node.memoryHigh | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          1 - (
            node_memory_MemAvailable_bytes{cluster_region="{{ .Values.clusterRegion }}"}
            / node_memory_MemTotal_bytes{cluster_region="{{ .Values.clusterRegion }}"}
          )
        ) * 100 > {{ .Values.rules.node.memoryCriticalThreshold }}
      for: 5m
      labels:
        severity: critical
        cluster_region: {{ .Values.clusterRegion }}

    - alert: KubeNodeCPUSaturation
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} CPU usage is
          {{ "{{" }} printf "%.0f" $value {{ "}}" }}% on cluster {{ .Values.clusterRegion }}.
        summary: Node CPU saturation ({{ .Values.clusterRegion }})
        {{- with (.Values.runbooks.node.cpuSaturation | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          1 - avg by (instance, cluster_region) (
            rate(node_cpu_seconds_total{
              mode="idle",
              cluster_region="{{ .Values.clusterRegion }}"
            }[5m])
          )
        ) * 100 > {{ .Values.rules.node.cpuWarningThreshold }}
      for: 5m
      labels:
        severity: warning
        cluster_region: {{ .Values.clusterRegion }}

    - alert: KubeNodeCPUSaturation
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} CPU usage is
          {{ "{{" }} printf "%.0f" $value {{ "}}" }}% on cluster {{ .Values.clusterRegion }}.
          Immediate action required.
        summary: Node CPU critically saturated ({{ .Values.clusterRegion }})
        {{- with (.Values.runbooks.node.cpuSaturation | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          1 - avg by (instance, cluster_region) (
            rate(node_cpu_seconds_total{
              mode="idle",
              cluster_region="{{ .Values.clusterRegion }}"
            }[5m])
          )
        ) * 100 > {{ .Values.rules.node.cpuCriticalThreshold }}
      for: 5m
      labels:
        severity: critical
        cluster_region: {{ .Values.clusterRegion }}

    - alert: KubeNodeFilesystemAlmostFull
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} root filesystem is
          {{ "{{" }} printf "%.0f" $value {{ "}}" }}% full on cluster {{ .Values.clusterRegion }}.
        summary: Node root filesystem almost full ({{ .Values.clusterRegion }})
        {{- with (.Values.runbooks.node.filesystemAlmostFull | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          1 - (
            node_filesystem_avail_bytes{
              cluster_region="{{ .Values.clusterRegion }}",
              mountpoint="/",
              fstype!~"tmpfs|fuse.lxcfs|squashfs"
            }
            / node_filesystem_size_bytes{
              cluster_region="{{ .Values.clusterRegion }}",
              mountpoint="/",
              fstype!~"tmpfs|fuse.lxcfs|squashfs"
            }
          )
        ) * 100 > {{ .Values.rules.node.diskWarningThreshold }}
      for: 10m
      labels:
        severity: warning
        cluster_region: {{ .Values.clusterRegion }}

    - alert: KubeNodeFilesystemAlmostFull
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} root filesystem is
          {{ "{{" }} printf "%.0f" $value {{ "}}" }}% full on cluster {{ .Values.clusterRegion }}.
          Immediate action required.
        summary: Node root filesystem critically full ({{ .Values.clusterRegion }})
        {{- with (.Values.runbooks.node.filesystemAlmostFull | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          1 - (
            node_filesystem_avail_bytes{
              cluster_region="{{ .Values.clusterRegion }}",
              mountpoint="/",
              fstype!~"tmpfs|fuse.lxcfs|squashfs"
            }
            / node_filesystem_size_bytes{
              cluster_region="{{ .Values.clusterRegion }}",
              mountpoint="/",
              fstype!~"tmpfs|fuse.lxcfs|squashfs"
            }
          )
        ) * 100 > {{ .Values.rules.node.diskCriticalThreshold }}
      for: 10m
      labels:
        severity: critical
        cluster_region: {{ .Values.clusterRegion }}

    - alert: KubeNodeInodesSaturation
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} inode usage is
          {{ "{{" }} printf "%.0f" $value {{ "}}" }}% on cluster {{ .Values.clusterRegion }}.
        summary: Node root filesystem inode saturation ({{ .Values.clusterRegion }})
        {{- with (.Values.runbooks.node.inodesSaturation | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          1 - (
            node_filesystem_files_free{
              cluster_region="{{ .Values.clusterRegion }}",
              mountpoint="/",
              fstype!~"tmpfs|fuse.lxcfs|squashfs"
            }
            / node_filesystem_files{
              cluster_region="{{ .Values.clusterRegion }}",
              mountpoint="/",
              fstype!~"tmpfs|fuse.lxcfs|squashfs"
            }
          )
        ) * 100 > {{ .Values.rules.node.inodeWarningThreshold }}
      for: 10m
      labels:
        severity: warning
        cluster_region: {{ .Values.clusterRegion }}

    - alert: KubeNodeInodesSaturation
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} inode usage is
          {{ "{{" }} printf "%.0f" $value {{ "}}" }}% on cluster {{ .Values.clusterRegion }}.
          Immediate action required.
        summary: Node root filesystem inodes critically saturated ({{ .Values.clusterRegion }})
        {{- with (.Values.runbooks.node.inodesSaturation | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          1 - (
            node_filesystem_files_free{
              cluster_region="{{ .Values.clusterRegion }}",
              mountpoint="/",
              fstype!~"tmpfs|fuse.lxcfs|squashfs"
            }
            / node_filesystem_files{
              cluster_region="{{ .Values.clusterRegion }}",
              mountpoint="/",
              fstype!~"tmpfs|fuse.lxcfs|squashfs"
            }
          )
        ) * 100 > {{ .Values.rules.node.inodeCriticalThreshold }}
      for: 10m
      labels:
        severity: critical
        cluster_region: {{ .Values.clusterRegion }}

    - alert: KubeNodeFilesystemSpaceFillingUp
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} root filesystem is predicted to fill up
          within 24 hours on cluster {{ .Values.clusterRegion }}.
        summary: Node root filesystem predicted to be full in 24h ({{ .Values.clusterRegion }})
        {{- with (.Values.runbooks.node.filesystemSpaceFillingUp | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          node_filesystem_avail_bytes{
            cluster_region="{{ .Values.clusterRegion }}",
            mountpoint="/",
            fstype!~"tmpfs|fuse.lxcfs|squashfs"
          } / node_filesystem_size_bytes{
            cluster_region="{{ .Values.clusterRegion }}",
            mountpoint="/",
            fstype!~"tmpfs|fuse.lxcfs|squashfs"
          } * 100 < 15
        )
        and
        predict_linear(
          node_filesystem_avail_bytes{
            cluster_region="{{ .Values.clusterRegion }}",
            mountpoint="/",
            fstype!~"tmpfs|fuse.lxcfs|squashfs"
          }[6h],
          86400
        ) < 0
      for: 1h
      labels:
        severity: warning
        cluster_region: {{ .Values.clusterRegion }}

    - alert: KubeNodePressure
      annotations:
        description: >
          Node {{ "{{" }} $labels.node {{ "}}" }} has {{ "{{" }} $labels.condition {{ "}}" }}
          pressure on cluster {{ .Values.clusterRegion }}.
        summary: Node pressure condition active ({{ .Values.clusterRegion }})
        {{- with (.Values.runbooks.node.pressure | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        kube_node_status_condition{
          condition=~"MemoryPressure|DiskPressure|PIDPressure",
          status="true",
          cluster_region="{{ .Values.clusterRegion }}"
        } == 1
      for: 10m
      labels:
        severity: warning
        cluster_region: {{ .Values.clusterRegion }}

    - alert: KubeNodeLoadHigh
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} normalized load is
          {{ "{{" }} printf "%.2f" $value {{ "}}" }}x on cluster {{ .Values.clusterRegion }}.
        summary: Node load saturation high ({{ .Values.clusterRegion }})
        {{- with (.Values.runbooks.node.loadHigh | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          node_load5{cluster_region="{{ .Values.clusterRegion }}"}
          /
          count by (instance, cluster_region) (
            node_cpu_seconds_total{
              mode="idle",
              cluster_region="{{ .Values.clusterRegion }}"
            }
          )
        ) > {{ .Values.rules.node.loadWarningRatio }}
      for: 10m
      labels:
        severity: warning
        cluster_region: {{ .Values.clusterRegion }}

    - alert: KubeNodeLoadHigh
      annotations:
        description: >
          Node {{ "{{" }} $labels.instance {{ "}}" }} normalized load is
          {{ "{{" }} printf "%.2f" $value {{ "}}" }}x on cluster {{ .Values.clusterRegion }}.
          Immediate action required.
        summary: Node load critically saturated ({{ .Values.clusterRegion }})
        {{- with (.Values.runbooks.node.loadHigh | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          node_load5{cluster_region="{{ .Values.clusterRegion }}"}
          /
          count by (instance, cluster_region) (
            node_cpu_seconds_total{
              mode="idle",
              cluster_region="{{ .Values.clusterRegion }}"
            }
          )
        ) > {{ .Values.rules.node.loadCriticalRatio }}
      for: 10m
      labels:
        severity: critical
        cluster_region: {{ .Values.clusterRegion }}
{{- end }}
