{{- if .Values.rules.pvc.enabled }}
{{- $sevWarn := ternary "wip_warning" "warning" .Values.rules.pvc.warningSuppressed }}
{{- $sevCrit := ternary "wip_critical" "critical" .Values.rules.pvc.criticalSuppressed }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-prometheus-rules.labels" . | nindent 4 }}
    gitops.jenkins-x.io/pipeline: namespaces
spec:
  groups:
  - name: kubernetes.pvc
    rules:
    - alert: KubePersistentVolumeFillingUp
      annotations:
        description: >
          PVC {{ "{{" }} $labels.namespace {{ "}}" }}/{{ "{{" }} $labels.persistentvolumeclaim {{ "}}" }}
          is {{ "{{" }} printf "%.0f" $value {{ "}}" }}% full on cluster {{ "{{" }} $labels.cluster_region {{ "}}" }}.
        summary: PVC is almost full ({{ "{{" }} $labels.cluster_region {{ "}}" }})
        {{- with (.Values.runbooks.pvc.fillingUp | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          kubelet_volume_stats_used_bytes
          / kubelet_volume_stats_capacity_bytes
          * 100
        ) > {{ .Values.rules.pvc.warningThreshold }}
      for: 10m
      labels:
        severity: {{ $sevWarn }}

    - alert: KubePersistentVolumeFillingUp
      annotations:
        description: >
          PVC {{ "{{" }} $labels.namespace {{ "}}" }}/{{ "{{" }} $labels.persistentvolumeclaim {{ "}}" }}
          is {{ "{{" }} printf "%.0f" $value {{ "}}" }}% full on cluster {{ "{{" }} $labels.cluster_region {{ "}}" }}.
          Immediate action required.
        summary: PVC is critically full ({{ "{{" }} $labels.cluster_region {{ "}}" }})
        {{- with (.Values.runbooks.pvc.fillingUp | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          kubelet_volume_stats_used_bytes
          / kubelet_volume_stats_capacity_bytes
          * 100
        ) > {{ .Values.rules.pvc.criticalThreshold }}
      for: 10m
      labels:
        severity: {{ $sevCrit }}

    - alert: KubePersistentVolumeInodesFillingUp
      annotations:
        description: >
          PVC {{ "{{" }} $labels.namespace {{ "}}" }}/{{ "{{" }} $labels.persistentvolumeclaim {{ "}}" }}
          inode usage is {{ "{{" }} printf "%.0f" $value {{ "}}" }}% on cluster {{ "{{" }} $labels.cluster_region {{ "}}" }}.
        summary: PVC inodes almost exhausted ({{ "{{" }} $labels.cluster_region {{ "}}" }})
        {{- with (.Values.runbooks.pvc.inodesFillingUp | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          kubelet_volume_stats_inodes_used
          / kubelet_volume_stats_inodes
          * 100
        ) > {{ .Values.rules.pvc.inodeWarningThreshold }}
        unless (
          kubelet_volume_stats_inodes == 0
        )
      for: 10m
      labels:
        severity: {{ $sevWarn }}

    - alert: KubePersistentVolumeInodesFillingUp
      annotations:
        description: >
          PVC {{ "{{" }} $labels.namespace {{ "}}" }}/{{ "{{" }} $labels.persistentvolumeclaim {{ "}}" }}
          inode usage is {{ "{{" }} printf "%.0f" $value {{ "}}" }}% on cluster {{ "{{" }} $labels.cluster_region {{ "}}" }}.
          Immediate action required.
        summary: PVC inodes critically exhausted ({{ "{{" }} $labels.cluster_region {{ "}}" }})
        {{- with (.Values.runbooks.pvc.inodesFillingUp | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          kubelet_volume_stats_inodes_used
          / kubelet_volume_stats_inodes
          * 100
        ) > {{ .Values.rules.pvc.inodeCriticalThreshold }}
        unless (
          kubelet_volume_stats_inodes == 0
        )
      for: 10m
      labels:
        severity: {{ $sevCrit }}

    - alert: KubePersistentVolumeFillingUpPredicted
      annotations:
        description: >
          PVC {{ "{{" }} $labels.namespace {{ "}}" }}/{{ "{{" }} $labels.persistentvolumeclaim {{ "}}" }}
          is predicted to fill up within {{ .Values.rules.pvc.predictFullInHours }} hours on cluster {{ "{{" }} $labels.cluster_region {{ "}}" }}.
        summary: PVC predicted to be full in {{ .Values.rules.pvc.predictFullInHours }}h ({{ "{{" }} $labels.cluster_region {{ "}}" }})
        {{- with (.Values.runbooks.pvc.fillingUpPredicted | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          kubelet_volume_stats_available_bytes
          / kubelet_volume_stats_capacity_bytes
          * 100 < 15
        )
        and
        predict_linear(
          kubelet_volume_stats_available_bytes[6h],
          {{ mul .Values.rules.pvc.predictFullInHours 3600 }}
        ) < 0
      for: 1h
      labels:
        severity: {{ $sevWarn }}

    - alert: KubePersistentVolumeErrors
      annotations:
        description: >
          PVC {{ "{{" }} $labels.persistentvolumeclaim {{ "}}" }} is in {{ "{{" }} $labels.phase {{ "}}" }}
          phase on cluster {{ "{{" }} $labels.cluster_region {{ "}}" }}.
        summary: PVC in Failed or Pending state ({{ "{{" }} $labels.cluster_region {{ "}}" }})
        {{- with (.Values.runbooks.pvc.errors | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        kube_persistentvolume_status_phase{
          phase=~"Failed|Pending"
        } > 0
      for: 5m
      labels:
        severity: {{ $sevCrit }}

    - alert: KubePersistentVolumeGrowthAbnormal
      annotations:
        description: >
          PVC {{ "{{" }} $labels.namespace {{ "}}" }}/{{ "{{" }} $labels.persistentvolumeclaim {{ "}}" }}
          is growing at {{ "{{" }} printf "%.0f" $value {{ "}}" }}% per day on cluster {{ "{{" }} $labels.cluster_region {{ "}}" }}.
        summary: PVC daily growth rate abnormal ({{ "{{" }} $labels.cluster_region {{ "}}" }})
        {{- with (.Values.runbooks.pvc.growthAbnormal | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          deriv(kubelet_volume_stats_used_bytes[1d])
          * 86400
          / kubelet_volume_stats_capacity_bytes
          * 100
        ) > {{ .Values.rules.pvc.growthRateWarning }}
      for: 1h
      labels:
        severity: {{ $sevWarn }}

    - alert: KubePersistentVolumeGrowthAbnormal
      annotations:
        description: >
          PVC {{ "{{" }} $labels.namespace {{ "}}" }}/{{ "{{" }} $labels.persistentvolumeclaim {{ "}}" }}
          is growing at {{ "{{" }} printf "%.0f" $value {{ "}}" }}% per day on cluster {{ "{{" }} $labels.cluster_region {{ "}}" }}.
          Immediate action required.
        summary: PVC daily growth rate critically high ({{ "{{" }} $labels.cluster_region {{ "}}" }})
        {{- with (.Values.runbooks.pvc.growthAbnormal | default .Values.runbooks.default) }}
        runbook_url: {{ . }}
        {{- end }}
      expr: |-
        (
          deriv(kubelet_volume_stats_used_bytes[1d])
          * 86400
          / kubelet_volume_stats_capacity_bytes
          * 100
        ) > {{ .Values.rules.pvc.growthRateCritical }}
      for: 1h
      labels:
        severity: {{ $sevCrit }}
{{- end }}
