{{- range .Values.clusterBindings }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .group }}
subjects:
  - kind: Group
    name: {{ $.Values.groupsPrefix }}{{ .group }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ .clusterRole }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
