bankVaultsImage: ghcr.io/banzaicloud/bank-vaults:latest

apiAddr: 'vault'
existingTlsSecretName: ""

image: hashicorp/vault:1.14

affinity: {}

vaultAnnotations:

# ingress:
#   enabled: true
#   annotations: {}
#   spec:
#     rules:
#       - host: vault.does.not.exist
#         http:
#           paths:
#           - backend:
#               service:
#                 name: vault
#                 port:
#                   number: 8200
#             path: /
#             pathType: ImplementationSpecific

istio:
  enabled: false

size: 3

auth:
  namespaces:
  - jx-vault

pvc:
  enabled: true
  storageClassName:
  size: 3Gi

# example "default"
customAuthRole: ""
# https://developer.hashicorp.com/vault/docs/configuration/storage/raft
disable_mlock: true
serviceRegistrationEnabled: true
multiRegion:
  # - sgp1
  # - sbg5
tlsAdditionalHosts: []
# multi-dc config
primary: true
raftLeaderAddress: "vault-primary.jx-vault.svc.cluster.local"
secretTlsPrimaryName: "vault-primary-tls"
logLevel: info

##
jxRequirements:
  ingress:
    annotations: {}

resources:
  requests:    
    cpu: '100m'
    memory: 128Mi
  limits:
    cpu: '100m'
    memory: 256Mi

vaultConfigurer:
  resources: {}