bankVaultsImage: ghcr.io/banzaicloud/bank-vaults:latest

existingTlsSecretName: ""

image: vault:1.12

vaultAnnotations:
  service.cilium.io/global: "true"

ingress:
  enabled: true
  annotations: {}
  spec:
    rules:
      - host: vault.does.not.exist
        http:
          paths:
          - backend:
              service:
                name: vault
                port:
                  number: 8200
            path: /
            pathType: ImplementationSpecific

istio:
  enabled: false

size: 1

auth:
  namespaces:
  - secret-infra

pvc:
  enabled: true
  storageClassName:
  size: 1Gi

# example "default"
customAuthRole: ""
