image:
  repository: ghcr.io/bryopsida/wireguard
  tag: main
  pullPolicy: Always
wireguard:
  #  -- Subnet for your VPN, take care not to clash with cluster POD cidr
  serverCidr: 10.34.0.1/24
  # -- A collection of clients that will be added to wg0.conf, accepts objects with keys PublicKey and AllowedIPs, stored in secret
  clients: []
service:
  # -- Whether the service will be created or not
  enabled: true
  # -- Service type, to keep internal to cluster use ClusterIP
  type: LoadBalancer
  # -- Service port, default is 51280 UDP
  port: 51280
  labels: {}
# -- Name of a secret with a wireguard private key on key privatekey, if not provided on first install a hook generates one.
secretName: ~
replicaCount: 3
resources:
  requests:
    memory: 256Mi
    cpu: "100m"
  limits:
    memory: 256Mi
    cpu: "100m"
deploymentStrategy:
  type: 'RollingUpdate'
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1
disruptionBudget:
  enabled: true
  minAvailable: 2
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
